# Generated by Django 6.0 on 2025-12-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
