# Generated by Django 6.0 on 2025-12-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_tipo'),
    ]

    operations = [
    ]
